USGS-NLCD
stactools-packages/usgs-nlcd pull request #2
Opened 2021-10-19 22:26 UTC by tomer-rockman

**Description:**
Still need to add read me 

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [x] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2021-10-20 07:19 UTC, cuttlefish commented on src/stactools/usgs_nlcd/constants.py
> +/license.txt"""
The file linked here just got deleted from the repo. What's the plan for this?
The triple quotes will include a line ending in the middle of the string which won't work for a URL.

2021-10-20 07:25 UTC, cuttlefish commented on src/stactools/usgs_nlcd/constants.py
> +                    title="Public Domain License - USGS")
For the title, I'd refer to it as a "Waiver" rather than a "License"

2021-10-20 16:30 UTC, darrenwiens commented
Please add an `/examples` directory with example collection(s) and item

2021-10-21 04:31 UTC, cuttlefish commented on src/stactools/usgs_nlcd/stac.py
> +            media_type=MediaType.JPEG,
The thumbnail is a PNG

2021-10-22 19:13 UTC, darrenwiens approved these changes
I think it looks good - just change that one file type in examples

2021-10-22 19:13 UTC, darrenwiens commented on examples/collection.json
> +      "type": "image/jpeg",
Change to png

2021-10-22 19:32 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/stac.py
> +            media_type=MediaType.JPEG,
removed item thumbnail and corrected collection thumbnail

2021-10-22 19:39 UTC, tomer-rockman commented on examples/collection.json
> +      "type": "image/jpeg",
Changed

2021-10-22 23:08 UTC, cuttlefish requested changes

2021-10-22 23:08 UTC, cuttlefish commented on src/stactools/usgs_nlcd/commands.py
> +                  help="Path to an input GeoTiff")
The other commands here use arguments for the required parameters.
I think most of the stactools modules are using options for everything.
Either way, these should definitely be consistent within the module.

2021-10-22 23:08 UTC, cuttlefish commented on src/stactools/usgs_nlcd/commands.py
> +    def create_cog_command(destination: str, source: str, tile: bool) -> None:
Add a test for the create-cog Command. Ideally two, one with and one without tiling.

2021-10-22 23:08 UTC, cuttlefish commented on src/stactools/usgs_nlcd/stac.py
> +def create_item(cog_href: str) -> Item:
Will this work with un-tiled data? If not, we should probably just force the create-cog command to always tile.

2021-10-22 23:08 UTC, cuttlefish commented on src/stactools/usgs_nlcd/stac.py
> +        destination (str): Directory where the Item will be stored.
`destination` no longer exists

2021-10-22 23:08 UTC, cuttlefish commented on src/stactools/usgs_nlcd/stac.py
> +    item_projection = ProjectionExtension.ext(item, add_if_missing=True)
Add WK2 field to the proj extension

2021-10-25 18:21 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/commands.py
> +    def create_cog_command(destination: str, source: str, tile: bool) -> None:
I removed this test because it would require the inclusion of one the 20gb img/ige files. is there a workaround for that?

2021-10-25 18:42 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/stac.py
> +    item_projection = ProjectionExtension.ext(item, add_if_missing=True)
Added.

2021-10-25 18:44 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/stac.py
> +        destination (str): Directory where the Item will be stored.
Removed

2021-10-25 20:58 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/stac.py
> +def create_item(cog_href: str) -> Item:
Modified to accept both tiled and untiled

2021-10-25 21:16 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/commands.py
> +                  help="Path to an input GeoTiff")
Added options for all CLI commands

2021-10-25 21:45 UTC, tomer-rockman commented on src/stactools/usgs_nlcd/commands.py
> +    def create_cog_command(destination: str, source: str, tile: bool) -> None:
Decided to not include a test for this to avoid issues with img file

2021-10-25 21:47 UTC, merged